// let cardlest = document.querySelector('.card')
let cardlest = document.querySelector('#form')
let cardlest1 = document.querySelector('#form1')
let cardlest2 = document.querySelector('#form2')
let cardlest3 = document.querySelector('#form3')
let cardlest4 = document.querySelector('#form4')
let cardlest5 = document.querySelector('#form5')
let cardlest6 = document.querySelector('#form6')
let cardlest7 = document.querySelector('#form7')
let cardlest8 = document.querySelector('#form8')
let cardlest9 = document.querySelector('#form9')
let cardlest10 = document.querySelector('#form10')
let cardlest11 = document.querySelector('#form11')
let cardlest12 = document.querySelector('#form12')
let cardlest13 = document.querySelector('#form13')

cardlest.addEventListener('submit',makeorder)
 cardlest1.addEventListener('submit',makeorder)
 cardlest2.addEventListener('submit',makeorder)
 cardlest3.addEventListener('submit',makeorder)
 cardlest4.addEventListener('submit',makeorder)
 cardlest5.addEventListener('submit',makeorder)
 cardlest6.addEventListener('submit',makeorder)
 cardlest7.addEventListener('submit',makeorder)
 cardlest8.addEventListener('submit',makeorder)
 cardlest9.addEventListener('submit',makeorder)
 cardlest10.addEventListener('submit',makeorder)
 cardlest11.addEventListener('submit',makeorder)
 cardlest12.addEventListener('submit',makeorder)
 cardlest13.addEventListener('submit',makeorder)
// cardlest2.addEventListener('submit',makeorder)


// cardlest3.addEventListener('submit',makeorder)

